### ISSUE TITLE
Theoretical justification for the changes you made to the NICV computation

### ISSUE THREAD

**Issue by TotallyNotAStudent0** [Ledger-Donjon/lascar#35]
Hello,

In commit 189ad51, you completely changed the code responsible for this computation. Could you please provide a source with a theoretical justification (e.g - some kind of mathematical proof) or at least an explanation for the resulting metric, as it no longer matches the description from the original paper (for reference - NICV: Normalized Inter-Class Variance for Detection of Side-Channel Leakage, Shivam Bhasin, Jean-Luc Danger, Sylvain Guilley, Zakaria Najm, 2014).

Best regards,

TotallyNotAStudent0

**Comment by adrianthillard** [comment]
Hello, thank you for this question. 

The changes were made to fix the way that the numerator was computed, which was wrong. In the defining paper -that you cited-, the NICV is defined as the ratio between Var[E[Y|X]] on Var[Y]. The underlying issue that was fixed on this commit is the support on which Var[E[Y|X]] is taken.

In the old code, to compute Var[E[Y|X]], we did the following:
1. accumulate, in acc and acc2 respectively, for each x in X, E[Y|X=x] and E[Y|X=x]²
2. compute acc2/nb_partitions - (acc/nb_partitions)²

Nonetheless, this approach is flawed: we are not taking into account the probabilities on the underlying space of X.

If you look at the derivation of equation (4) in the paper, you can see that the correct definition of Var[E[Y|X]] indeed includes a probability P(X=x). 
This oversight in our code could sometimes produce wrong values for NICV, eg. values that would be greater than 1. 

As a simple example where this would have happened, consider X being a Bernoulli variable of parameter p, and Y = X, and consider that we have a large number of observations. In this case, we have two partitions (0 and 1), with respective expectations 0 and 1. The variable acc will hence be 0+1=1, and the variable acc2 0²+1²=1.
Consequently, the -wrong- evaluation of Var[E[Y|X]] would be 1/2 - (1/2)² = 1/4. 
Note how these values do not involve the underlying parameter p. Since Var[Y] = Var[X] = p*(1-p), hence the -wrong- NICV would be (1/4) / (p*(1-p)), which will be higher than 1 whenever p is different from 1/2.


We simply fixed the code by carefully computing Var[E[Y|X]].
1.a During our loop, we accumulate in acc the value acc_x_by_partition[0,i]², and divide it by the partition_count. Note that, in acc_x_by_partition[0,i], we have the sum of Y's for the partition i, that is, considering a large enough sample, E[Y|X=i] * partition_count[i]. Consequently, acc_x_by_partition[0,i]²/partition_count[i] = E[Y|X=i]² * partition_count[i].
1.b When dividing acc by total_number_of_traces, we get: sum(acc_x_by_partition[0,i]² * partition_count[i]/total_nb_of_traces). Note that partition_count[i]/total_nb_of_traces is P(X=i). Therefore, the result of acc/total_nb_of_traces is actually E[E[Y|X]²], where we carefully took into account the probability space of X.
2. Finally, we just use the variance formula : Var[E[Y|X]] = E[E[Y|X]²] - (E[E[Y|X]])², together with the law of total expectation, giving us E[E[Y|X]] = E[Y], which lay the identity: Var[E[Y|X]] = E[E[Y|X]²] - E[Y]².


Taking the same simple example as before, we would have E[Y|X=0]=0, E[Y|X=1]=1, and hence E[E[Y|X]²]=q*0+p*1=p. We would also have E[Y]=E[X]=p, and Var[Y]=Var[X]=p(1-p)=p-p². Consequently, the NICV would be (p-p²)/(p-p²)=1 for any p.

We did our best to double check these results, but oversights are always possible. Please do not hesitate to signal any issue or mistake.

Best regards,
Adrian

**Comment by TotallyNotAStudent0** [comment]
Hello,

Thank you very much for this detailed answer. I now understand the changes you made to your code and am able to follow your reasoning very easily.

I am closing this issue as I am convinced by your comment.

Best Regards,

TotallyNotAStudent0
